version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: proveedorGestor
    ports:
      - '3306'

  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    networks:
      - symfony

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###


